# Generated by Django 4.2 on 2023-07-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clinical_attendance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regs.clinicalattendance",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.hospital",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="lab_tests",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regs.speciallaboratorytests",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mc_transmission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regs.motherchildtransmission",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mother_visit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regs.motherfirstvisit",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="pregnancy_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regs.previouspregnancyinformation",
            ),
        ),
    ]
