# Generated by Django 4.2 on 2023-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("P", "Patient"),
                    ("H", "Hospital"),
                    ("R", "Regulator"),
                    ("S", "Researcher"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
