# Generated by Django 4.2 on 2023-07-05 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_patient_clinical_attendance_patient_hospital_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="clinical_attendance",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="lab_tests",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mc_transmission",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mother_visit",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="pregnancy_info",
        ),
        migrations.AlterField(
            model_name="patient",
            name="hospital",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.hospital",
            ),
            preserve_default=False,
        ),
    ]
