# Generated by Django 4.2 on 2023-06-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researcher",
            old_name="res_national_id",
            new_name="national_id",
        ),
    ]
