# Generated by Django 4.2 on 2023-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_res_national_id_researcher_national_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researcher",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
