# Generated by Django 4.2 on 2023-06-29 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_researcher_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="fname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="lname",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="password",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="regulator_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="regulator_position",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="username",
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(default=datetime.date(1930, 5, 18)),
        ),
    ]
