# Generated by Django 4.2 on 2023-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_fname_patient_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="hospital_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
