# Generated by Django 4.2 on 2023-06-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_hospital_hospital_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulator",
            name="regulator_id",
        ),
    ]
