# Generated by Django 4.2 on 2023-06-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patient",
            new_name="SpecialLaboratoryTests",
        ),
    ]
