# Generated by Django 4.2 on 2023-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0002_rename_patient_speciallaboratorytests"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreviousPregnancyInfo",
            new_name="MotherFirstVisit",
        ),
        migrations.RenameModel(
            old_name="Pregnancy",
            new_name="PreviousPregnancyInformation",
        ),
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
            ),
        ),
    ]
