# Generated by Django 4.2 on 2023-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0003_rename_previouspregnancyinfo_motherfirstvisit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalattendance",
            name="weight",
            field=models.PositiveIntegerField(
                max_length=20, verbose_name="Weight (Kg)"
            ),
        ),
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="blood_count",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="other_tests",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="proteinuria",
            field=models.CharField(),
        ),
    ]
