# Generated by Django 4.2 on 2023-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0004_alter_clinicalattendance_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciallaboratorytests",
            name="id",
        ),
        migrations.AddField(
            model_name="speciallaboratorytests",
            name="labtest_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="clinicalattendance",
            name="tetanus_vaccine",
            field=models.CharField(
                choices=[
                    ("0", "Not Yet"),
                    ("tt1", "TT1"),
                    ("tt2", "TT2"),
                    ("tt3", "TT3"),
                    ("tt4", "TT4"),
                    ("tt5", "TT5"),
                ],
                max_length=4,
                verbose_name="Tetanus Vaccine",
            ),
        ),
    ]
