# Generated by Django 4.2 on 2023-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0005_remove_speciallaboratorytests_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="labtest_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
