# Generated by Django 4.2 on 2023-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0006_alter_speciallaboratorytests_labtest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciallaboratorytests",
            name="labtest_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
