# Generated by Django 4.2 on 2023-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regs", "0007_alter_speciallaboratorytests_labtest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalattendance",
            name="weight",
            field=models.PositiveIntegerField(verbose_name="Weight (Kg)"),
        ),
        migrations.AlterField(
            model_name="motherchildtransmission",
            name="mc_personnel_sign",
            field=models.CharField(
                max_length=100, verbose_name="Sign of the MC Personnel"
            ),
        ),
    ]
